version: '3.9'
services:
  postgres-spring:
    image: postgres:15
    container_name: postgres-spring
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB: springdb
    ports:
      - "5432:5432"
    secrets:
      - postgres_password
    restart: unless-stopped

secrets:
  postgres_password:
    file: ./secrets/postgres_password.txt
